### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by cryan10** [pratik227/vue3-json-excel#11]
**Describe the bug**
While using vue3-excel-json in my project, a warning appears via Snyk because of the SheetJS dependency (xlsx@0.18.5).

**Expected behavior**
According to Snyk, this issue was resolved in version 0.19.3 of SheetJS

**Screenshots**
![SnykError](https://github.com/pratik227/vue3-json-excel/assets/20429792/bb834624-1348-43b3-bd11-34836ae45883)

**Additional context**
This issue should be resolved by updating the dependencies of the project.

**Comment by pratik227** [comment]
Hi @cryan10,

Thanks for details. but I have only one dependancy that is "xlsx": "^0.18.5" and it's latest version. So not sure how I can fix it maybi add SheetJS in dependancy with latest version. But not sure it will fix the issue or not

Thanks,
Pratik Patel

**Comment by pratik227** [comment]
actually I just checked xlsx don't have any dependancy on sheetjs

https://npm.anvaka.com/#/view/2d/xlsx

**Comment by cryan10** [comment]
Hi, thank you for taking a look! SheetJS appears to be the friendly/marketing name for the package: https://www.npmjs.com/package/xlsx

Their docs say that the NPM registry is out of date: https://docs.sheetjs.com/docs/getting-started/installation/nodejs

But I just saw the warning about Snyk error I mentioned, and how it's a false flag being raised. Sorry I didn't see that sooner. Happy to close this out if you do not want to update the dependencies at this time.

**Comment by pratik227** [comment]
Hi @cryan10,

Just released the new version(1.0.19) with updated dependancy. Can you check and let me know if it works.

Thanks,
Pratik Patel

**Comment by cryan10** [comment]
Thank you! Unfortunately Snyk is still throwing the error, but based on SheetJS's own warning about this in their docs, I'm good with closing out this issue. Thank you again for taking a look and handling this!
