### ISSUE TITLE
Nested Data is not parsed correctly

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [pratik227/vue3-json-excel#13]
**Describe the bug**
Trying the example data nested objects get stringified to [object Object]

![grafik](https://github.com/pratik227/vue3-json-excel/assets/86342787/6f5c6259-283b-45bc-b894-777681d9bb10)

**Comment by pratik227** [comment]
```
json_fields: {
      "Complete name": "name",
      City: "city",
      Telephone: "phone.mobile",
      "Telephone 2": {
        field: "phone.landline",
        callback: (value) => {
          return `Landline Phone - ${value}`;
        },
      },
    },
```
 Have you tried this ?

https://github.com/pratik227/vue3-json-excel?tab=readme-ov-file#example

**Comment by pratik227** [comment]
Use callback https://vue-json-excel3.netlify.app/using-callbacks-examples.html

**Comment by sschneider-ihre-pvs** [comment]
okay it works with field but I just want the data as is without a mapping

**Comment by pratik227** [comment]
Object can't directly converted refer this example. https://vue-json-excel3.netlify.app/using-callbacks-examples.html

**Comment by sschneider-ihre-pvs** [comment]
oh i get it, how should the parser know what to reduce it to.

**Comment by pratik227** [comment]
Closing this issue
