### ISSUE TITLE
How to set csv file to UTF-8 ?

### ISSUE THREAD

**Issue by IrisChi** [pratik227/vue3-json-excel#14]
Hi, there are many chinese words in my json, is there any key for setting UTF-8 in csv file ?
Thanks!

**Comment by pratik227** [comment]
Hi @IrisChi,

```
json_meta: [
      [
        {
          key: "charset",
          value: "utf-8",
        },
      ],
    ],
```

Can you try ```:meta="json_meta"``` 

Thanks,
Pratik Patel

**Comment by IrisChi** [comment]
Hi @pratik227 ,
![image](https://github.com/pratik227/vue3-json-excel/assets/1622599/bf440dd9-0b99-4a41-988d-ef89987e618d)
I tried, but still not work QQ
Thanks for answering

**Comment by pratik227** [comment]
Hi @IrisChi,

What should be the output sorry I didn't get it.

Thanks,
Pratik Patel

**Comment by IrisChi** [comment]
Hi @pratik227 ,
![image](https://github.com/pratik227/vue3-json-excel/assets/1622599/9e38f835-91a6-4fff-83f0-cae9e8ae9949)
The screenshot is the output file opened with Notepad++, and the data of the 'name' column is chinese words. 
When I use google spreadsheets to import this file, the result was correct.
I think maybe its the problem of excel in windows.
Thanks !

**Comment by pratik227** [comment]
Ok great
