### ISSUE TITLE
Download excel by event

### ISSUE THREAD

**Issue by huangganggui** [pratik227/vue3-json-excel#16]
This is very nice project and works well in vue template.

But i have a question about how to  donwload excel by event.
I want to emit a download event in  onMount() function, but i dont know how to do it.

Can some one help me? Thx.

**Comment by pratik227** [comment]
Hi @huangganggui,

You can do these using ref. Please find below example.


`<JsonExcel :data="json_data" ref="excel_ref">
      Download Data
      <img src="download_icon.png"/>
    </JsonExcel>
`

`  mounted() {
    this.$refs.excel_ref.generate()
  }`

Thanks,
Pratik Patel

**Comment by huangganggui** [comment]
Nice! work well, Thx a lot again. @pratik227
