### ISSUE TITLE
Fetch doesn't download any file

### ISSUE THREAD

**Issue by missmay4** [pratik227/vue3-json-excel#21]
Hi! 

I'm using this library in my project, I'm using the Fetch option, because i need to charge the data only when i click button. The thing is, the call makes it perfectly but no file is downloaded in my computer.

I noticed that when I click the button with fetch option, the data is saved. Then, if I create another button that not include fetch but has :data the download starts, but I need to do all only in one click. 

Is there any chance to make fetch call and get file downloaded at the same time with one button? 

Thanks in advice!

```
<download-excel
  v-if="!json_csv_ok"
  class="btn btn-outline-primary"
  :fetch="getUsers"
  :fields="json_fields"
  :before-finish="finishDownload"
>
  Generate CSV
</download-excel>
<download-excel
  v-if="json_csv_ok"
  class="btn btn-outline-primary"
  type="csv"
  name="Users.csv"
  :data="users_csv"
>
  <i class="bi bi-file-arrow-down-fill" />
  Download CSV
</download-excel>

json_fields: {
  'Complete name': 'name',
  'Email': 'email',
  'Geography': 'geography',
  'Registration date': 'registration_date',

async getUsers() {
  usersService.get_users({ limit: -1, offset: 0, filters: {} }).then((response) => {
        this.users_csv = []

        let aux = response.data.data
        if (aux.length !== 0) {
          for (let i in aux) {
            this.users_csv.push({
              name: aux[i].name,
              email: aux[i].email,
              geography: aux[i].geography.name,
              registration_date: aux[i].registration_date
            })
          }
        }
        this.json_csv_ok = true
        return this.users_csv
  })
}
```

**Comment by pratik227** [comment]
Hi @missmay4,

Please refer below code.
```

<template>
  <q-page class="">
    <download-excel
      class="btn"
      :fetch="fetchData"
      :before-generate="startDownload"
      :before-finish="finishDownload"
      type="xlsx" worksheet="My Worksheet"
      name="filename.xlsx"
    >
      Download Excel (you can customize this with html code!)
    </download-excel>
  </q-page>
</template>

<script>
import {defineComponent} from 'vue';
import JsonExcel from "vue-json-excel3";
import axios from 'axios';

export default defineComponent({
  name: 'IndexPage',
  components: {
    downloadExcel: JsonExcel
  },
  data() {
    return {
    }
  },
  methods: {
    async fetchData() {
      let repoUrl = 'https://jsonplaceholder.typicode.com/users';
      return axios.get(repoUrl)
        .then((response) => {
          console.log(response.data)
          return response.data;
        })
        .catch((error) => {
          this.persons = error.response.statusText;
        });
    },
    startDownload() {
      alert('show loading');
    },
    finishDownload() {
      alert('hide loading');
    }
  }
});
</script>

```

**Comment by missmay4** [comment]
Hi again! 
Thanks for the quick response. 

I tried it but, still the same... call is done but no file is downloaded in my computer. 

I'm using version"^1.0.18", maybe this could be the problem? 


Thanks.

**Comment by pratik227** [comment]
> Hi @missmay4,
> 
> Please refer below code.
> 
> ```
> 
> <template>
>   <q-page class="">
>     <download-excel
>       class="btn"
>       :fetch="fetchData"
>       :before-generate="startDownload"
>       :before-finish="finishDownload"
>       type="xlsx" worksheet="My Worksheet"
>       name="filename.xlsx"
>     >
>       Download Excel (you can customize this with html code!)
>     </download-excel>
>   </q-page>
> </template>
> 
> <script>
> import {defineComponent} from 'vue';
> import JsonExcel from "vue-json-excel3";
> import axios from 'axios';
> 
> export default defineComponent({
>   name: 'IndexPage',
>   components: {
>     downloadExcel: JsonExcel
>   },
>   data() {
>     return {
>     }
>   },
>   methods: {
>     async fetchData() {
>       let repoUrl = 'https://jsonplaceholder.typicode.com/users';
>       return axios.get(repoUrl)
>         .then((response) => {
>           console.log(response.data)
>           return response.data;
>         })
>         .catch((error) => {
>           this.persons = error.response.statusText;
>         });
>     },
>     startDownload() {
>       alert('show loading');
>     },
>     finishDownload() {
>       alert('hide loading');
>     }
>   }
> });
> </script>
> ```

These same code is working fine for me(Chrome Version 124.0.6367.119 (Official Build) (arm64)
). Make sure you have not blocked the download.

<img width="1412" alt="image" src="https://github.com/pratik227/vue3-json-excel/assets/34883558/a0bde8ee-fd45-4640-ad0b-db6f8eb0c9eb">


"vue-json-excel3": "^1.0.20"

**Comment by missmay4** [comment]
Um.. no the downloaded never appear, is strange.
The only diff with your code is that I'm not using quasar.

**Comment by pratik227** [comment]
Yah it should work is there any error in console can you try with static data it's working ?

**Comment by missmay4** [comment]
Negative, no errors appears :(

**Comment by pratik227** [comment]
Can you share any sample vue repo so I can check with sample data ?

**Comment by pratik227** [comment]
Closing issue bcz of inactive
