### ISSUE TITLE
RTL direction

### ISSUE THREAD

**Issue by hamedg68** [pratik227/vue3-json-excel#22]
add RTL mode for this lib

**Comment by pratik227** [comment]
Hi @hamedg68,

Added RTL support in xlsx only. Please try with newer version(**1.0.23**). 

`<download-excel
      class="btn"
      :fetch="fetchData"
      :before-generate="startDownload"
      :before-finish="finishDownload"
      type="xlsx" worksheet="My Worksheet"
      name="filename.xlsx"
      :rtl="true"
    >
      Download Excel (you can customize this with html code!)
    </download-excel>
`

Thanks,
Pratik Patel

**Comment by pratik227** [comment]
https://github.com/pratik227/vue3-json-excel/pull/24
