### ISSUE TITLE
SheetJS Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by hardikzignuts** [pratik227/vue3-json-excel#26]
When I'm installing node package dependencies for my project. I got the list of vulnerabilities and on running `npm audit`, I got the following thing.

![image](https://github.com/user-attachments/assets/10624d7b-888f-40dd-8d7f-f4a2c5468b3f)

You are using xlsx node package to develop vue3-json-excel 

When I checked the following link...

https://github.com/advisories/GHSA-5pgg-2g8v-p4x9

I realise that there is already fix available for this vulnerabilities with version 0.20.2 of xlsx. But I think you are not using this version while developing vue3-json-excel package even in latest version.

So, If you develop vue3-json-excel with version 0.20.2 of xlsx, I think this can be resolved.

Please let me know your thoughts on this and about your plan to fix this vulnerabilities.

Thanks in Advanced

**Comment by pratik227** [comment]
Hi @hardikzignuts,

I'm already using     

**"xlsx": "https://cdn.sheetjs.com/xlsx-0.20.2/xlsx-0.20.2.tgz"**

You can check in package.json file.

Also, 

![image](https://github.com/user-attachments/assets/0e95683d-cd19-4b2d-a6f3-8ffe3db7a0da)

https://github.com/pratik227/vue3-json-excel/issues/11

Please let me know if you need more information.

Thanks,
Pratik Patel

**Comment by hardikzignuts** [comment]
Hello @pratik227 

Yes, you are correct. I have checked. My issue is resolved now. Now I'm closing the issue.

Thanks for you reply and help
Hardik Patel
