### ISSUE TITLE
Format cells

### ISSUE THREAD

**Issue by seetpalsingh** [pratik227/vue3-json-excel#27]
**Is your feature request related to a problem? Please describe.**
I need to format the cells font-size and color and column min-width

**Describe the solution you'd like**
I see you added some format options in v1.0.24. But m not clear how to get my requirements done.

**Describe alternatives you've considered**
I got some hint code but not working with your plugin. have a look for chat GPT code:

```

    const jsonData = ref([
      { name: 'John Doe', age: 30, email: 'john@example.com' },
      { name: 'Jane Doe', age: 25, email: 'jane@example.com' },
      // Add more data as needed
    ]);

    const exportData = () => {
      const options = {
        fileName: 'example',
        sheet: {
          data: jsonData.value,
          autoWidth: true,
          fontSize: 12,  // Set font size to 12px
          columnsWidth: [
            { name: 'name', width: 30 }, // Adjust width for the name column
            { name: 'age', width: 20 },  // Adjust width for the age column
            { name: 'email', width: 50 } // Adjust width for the email column
          ],
        }
      };
      
      // Trigger the export with the specified options
      JsonExcel.export(options);
    };


```

**Additional context**
Please help, m got only tomorrow left to deliver.

**Comment by pratik227** [comment]
Hi @seetpalsingh,

It's available in latest version.

https://github.com/pratik227/vue3-json-excel/pull/28.

Doc - https://vue-json-excel3.netlify.app/cell-format-xlsx-examples.html#for-setting-widths-of-columns-supported-after-1-0-26

Thanks,
Pratik Patel

**Comment by seetpalsingh** [comment]
HI , i need color formats and padding ,spacing, background colors

**Comment by pratik227** [comment]
@seetpalsingh Don't have buffer right now. I will try
