### ISSUE TITLE
before-finish function not working

### ISSUE THREAD

**Issue by AttiZK** [pratik227/vue3-json-excel#31]
**Describe the bug**
I wanted to use an ajax loader icon when I click the excel download button, and switch it back to static icon when download finished. 

**To Reproduce**

 download-excel
					:fetch="json_data"
					:fields="json_fields"
					name="Kockázatok-leltár.xlsx"
					worksheet="Leltár"
					type="xlsx"
					:before-generate="excelClicked"
					:before-finish="excelDownloaded"
				
methods:{
...
excelClicked() {
			this.$notify({ title: 'Előkészítjuk az excel fájlt', type: 'success' });
			this.excelLoading = true;
		},

		excelDownloaded() {
			console.log('download finished');
			this.$notify({ title: 'A fájl készen van', type: 'success' });
			this.excelLoading = false;
		},
		
...
}

**Expected behavior**
The "before-generate" works fine, I get the loader icon, but "before-finish" does not. So the icon never switches back to static icon.

**Additional context**
I'm using latest 1.0.29 package version in Vite/vue.js3

In your code I see
if (!data || !data.length) {
	            if (typeof this.beforeFinish === "function") await this.beforeFinish();
	            return;
	          }

Does this mean it's not supposed to work if I use :data instead of :fetch? Or is it not related?

**Comment by pratik227** [comment]
Hi @AttiZK ,

Use 1.0.30 version. Let me know if it works.

Thanks,
Pratik Patel

**Comment by AttiZK** [comment]
Yes, this update seems to have solved it! Thanks a lot!
