### ISSUE TITLE
we need type .xlsx

### ISSUE THREAD

**Issue by FiveFrogSix** [pratik227/vue3-json-excel#7]
I love you

**Comment by pratik227** [comment]
Hi @FiveFrogSix,

Doc - https://vue-json-excel3.netlify.app/export-xlsx-examples.html

JFI it's available in new version.

Don't forget to check out my sponsorship page any support will be appreciated !!

[Sponsor❤️ ❤️ ](https://github.com/sponsors/pratik227) 

Thanks,
Pratik Patel

**Comment by FiveFrogSix** [comment]
@pratik227 Thank you so much <3
